apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-app.name" . }}
  labels:
    app: {{ include "sample-app.name" . }}
    chart: {{ include "sample-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "sample-app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "sample-app.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.image.frontend.name }}
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - name: sample-app-port
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_nginx_status
              port: sample-app-port
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /app/test
              port: sample-app-port
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
        - name: {{ .Values.image.backend.name }}
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - name: liveness-port
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /test
              port: liveness-port
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
