apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sample-app.name" . }}
  namespace: default
  labels:
    app: {{ include "sample-app.name" . }}
    chart: {{ include "sample-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ include "sample-app.name" . }}
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 15
