apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-app.name" . }}
  labels:
    app: {{ include "sample-app.name" . }}
    chart: {{ include "sample-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "sample-app.name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: sample-app-port
      protocol: TCP
